# Generated by Django 4.2.3 on 2023-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
